export const GRAMMAR_TOPICS = {
  A1: [
    "Personalpronomen (ich, du, er...)",
    "Konjugation im Präsens",
    "Bestimmter und unbestimmter Artikel",
    "Negation (nicht, kein)",
    "Possessivartikel (mein, dein...)",
    "Präpositionen mit Akkusativ",
    "Satzbau: Hauptsätze",
    "W-Fragen",
  ],
  A2: [
    "Perfekt (haben/sein)",
    "Präteritum (Modalverben, sein, haben)",
    "Reflexive Verben",
    "Präpositionen mit Dativ",
    "Wechselpräpositionen",
    "Vergleiche (Komparativ, Superlativ)",
    "Nebensätze (weil, dass, wenn)",
    "Adjektivdeklination",
  ],
  B1: [
    "Passiv Präsens",
    "Konjunktiv II (Wünsche, Höflichkeit)",
    "Relativsätze",
    "Futur I",
    "Genitiv",
    "Infinitiv mit 'zu'",
    "Präpositionen mit Genitiv",
    "Partizipialattribute",
  ],
  B2: [
    "Passiv in allen Zeitformen",
    "Konjunktiv II (Irreale Bedingungen)",
    "Nominalisierung",
    "Zweiteilige Konnektoren (nicht nur... sondern auch)",
    "Partizip I und II als Adjektive",
    "Verben mit festen Präpositionen",
    "Subjektive Bedeutung der Modalverben",
  ],
  C1: [
    "Konjunktiv I (Indirekte Rede)",
    "Passiversatzformen",
    "Komplexe Satzstrukturen",
    "Nomen-Verb-Verbindungen",
    "Präpositionaladverbien",
    "Nuancen der Modalpartikeln",
    "Wortbildung (Präfixe, Suffixe)",
  ],
  C2: [
    "Stilistische Nuancen",
    "Archaische Formen",
    "Wissenschaftssprache",
    "Idiomatische Redewendungen",
    "Komplexe Textkohärenz",
    "Rhetorische Mittel",
  ],
};

export const LEVELS = ["A1", "A2", "B1", "B2", "C1", "C2"];
